### ISSUE TITLE
Unable to save changes to Filename Pattern Replacer

### ISSUE THREAD

**Issue by systemmonkey42** [revenz/FileFlows#326] opened 2022-09-22 18:01 UTC
After creating a `Filename Pattern Replacer` node in a flow, attempts to edit the patterns fail silently.

chrome console logs show messages like the following;
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FileFlows.Client.Shared.NavMenu.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
window.Module.s.printErr @ blazor.webassembly.js:1
```

If I repeat the edit a few times, it might save, but it is not predictable, and is not helped by reloading the page.

**Comment by revenz** [comment] 2022-09-22 19:58
I believe its what is in your filename pattern replacer.  can you post what you have saved.  i cannot reproduce it myself.

**Comment by systemmonkey42** [comment] 2022-09-22 23:54
For me, I simple create a new filename replacer.  I added the pattern `left` and the replacement `right` (literally, just replaced left with right) and saved it.

I then double-clicked on it (its not wired into any other nodes at this point), and in the new field, I added `front` as a new pattern and `back` as the replacement.  Hit save.

I double-clicked again, and when it opens up, there is only `left`/`right`, not `front`/`back`.   

It really doesn't matter.  I think the rule it is has to have more than one replacement.  Once you have more than one pattern (eg, if you made multiple when it was initially created), you then can't edit any of the patterns.

**Comment by systemmonkey42** [comment] 2022-09-24 03:04
Are you still unable to reproduce this?

**Comment by revenz** [comment] 2022-09-24 04:48
I can't repo this, but its possible I fixed this with another ticket.   

I'll leave this open and ask you to test this in 1.0.4 when that's released.

**Comment by revenz** [comment] 2022-10-04 07:29
closing as believe to be fixeed

**Closed by revenz** 2022-10-04 07:29 UTC
