### ISSUE TITLE
Title of failing function node not displayed in file-info view

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#132] opened 2022-06-21 08:58 UTC
I have a "Fail Flow" Function node with no ouputs and this simple code
```JS
return -1;
```

When that node gets executed the info overview does only show "Function" instead of the actual node name. 

![image](https://user-images.githubusercontent.com/20821976/174760216-52d8cadb-ab98-4791-ab44-de10115275cc.png)

**Comment by revenz** [comment] 2022-06-28 03:49
can you try 0.8.3 (or later) and if it still occurs export the flow and post it here.

closing as cannot reproduce

**Comment by GamerBene19** [comment] 2022-06-28 12:52
I can't reopen the issue, but it still occurs. The last time it happend was ~9h ago with server and client on latest version. I'll try to create an example flow where the issue occurs

**Comment by GamerBene19** [comment] 2022-07-02 15:54
This simple flow reliably reproduces the issue for me with the latest version (8.4.1599)

```json
{
  "Enabled": true,
  "Description": "A blank Video template with a single \u0022Video File\u0022 input node.",
  "Type": 0,
  "Template": "Video File",
  "Parts": [
    {
      "Uid": "3e3bd3cb-b67c-4a83-910b-9c6f19f8d272",
      "Name": "",
      "FlowElementUid": "FileFlows.VideoNodes.VideoFile",
      "xPos": 450,
      "yPos": 50,
      "Icon": "fas fa-video",
      "Label": "",
      "Inputs": 0,
      "Outputs": 1,
      "OutputConnections": [
        {
          "Input": 1,
          "Output": 1,
          "InputNode": "8e73b8f9-2183-4dca-9d4e-135c5a24dc98"
        }
      ],
      "Type": 0,
      "Model": null
    },
    {
      "Uid": "8e73b8f9-2183-4dca-9d4e-135c5a24dc98",
      "Name": "Fail flow",
      "FlowElementUid": "FileFlows.BasicNodes.Functions.Function",
      "xPos": 450,
      "yPos": 170,
      "Icon": "fas fa-code",
      "Label": "",
      "Inputs": 1,
      "Outputs": 0,
      "OutputConnections": null,
      "Type": 3,
      "Model": {
        "Outputs": 0,
        "Code": "return -1;"
      }
    }
  ],
  "Uid": "78a1840f-95ed-42b1-9486-c6a1b88a4bee",
  "Name": "Always Failing",
  "DateCreated": "2022-07-02T10:23:56.7780129+00:00",
  "DateModified": "2022-07-02T10:23:57.3745511+00:00"
}
```

**Comment by revenz** [comment] 2022-07-08 22:39
fixed.
Only happened if name of function started with an "f" as it was mistakenly only using the first letter of the name and uid to compare if name was the UID

**Closed by revenz** 2022-07-08 22:39 UTC
