### ISSUE TITLE
Processed files are being moved to unprocessed after completion

### ISSUE THREAD

**Issue by aStonedPenguin** [revenz/FileFlows#204] opened 2022-07-14 18:35 UTC
Version: Latest Docker build

Processed files are being moved back to unprocessed while the original file is being replaced. They then get re-processed and show no file size change.

Enabling "Reprocess Recreated Files" in library settings seems to be the cause.

![img](https://cdn.discordapp.com/attachments/911564792521711657/997191489400606760/LightcoralSpittlebug.png)
![img](https://i.imgur.com/sLWeAJw.png)
![img](https://i.imgur.com/NrqFMWk.png)

**Comment by revenz** [comment] 2022-07-14 21:34
Can't reproduce this.

can you give me step by step from a clean install reproduction steps that will produce this issue?

I've tried
- create a flow that remuxes to mp4 (using mkv and move files) that replace original
- library set to reprocess recreated files, fingerprinting on 
- test files all converted to mp4.   scanned multiple times, no duplicates found or files added for reprocessing.    using sqlite
-

**Comment by revenz** [comment] 2022-07-14 22:13
Fixed, will be in 0.9.1.  turn off the reprocess setting for now

**Closed by revenz** 2022-07-14 22:13 UTC
