### ISSUE TITLE
Unable to encode Plex Dvr recordings

### ISSUE THREAD

**Issue by Flash1a** [revenz/FileFlows#10] opened 2022-02-24 03:56 UTC
Great software, I would like to be able to use this to re-encode my Plex drv recordings, however, the plex dvr file is unable to be encoded with the error in the log as follows.

2022-02-24 15:36:46.4937 - INFO -> [mp4 @ 0000015e7cc5e040] Could not find tag for codec dvb_teletext in stream #2, codec not currently supported in container
2022-02-24 15:36:46.4943 - INFO -> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
2022-02-24 15:36:46.4952 - ERRR -> Error initializing output stream 0:0 -- 
2022-02-24 15:36:46.4969 - INFO -> 
2022-02-24 15:36:46.4981 - INFO -> encoded 0 frames
2022-02-24 15:36:46.4990 - ERRR -> Conversion failed!

I tried use the remove subtitle node to remove the dvb_teletext to no avail

**Comment by revenz** [comment] 2022-02-24 03:57
could you upload a sample somewhere and provide an export of your flow?

**Comment by Flash1a** [comment] 2022-02-24 04:09
This is my flow
[Convert Plex DVR (1).zip](https://github.com/revenz/FileFlows/files/8129573/Convert.Plex.DVR.1.zip)

**Comment by revenz** [comment] 2022-02-24 04:21
only thing I can see from that flow is it might be MP4?  Have you tried mkv?
If you provide me a sample with that dvb_teletext stream I can investigate futher.

**Comment by Flash1a** [comment] 2022-02-24 04:34
yes tried mkv, the first time i tried mp4.  I could share a dvr file with you with resilio sync. could email you a link?

they are rather large recordings. sorry not the best at this sort of thing.

**Comment by revenz** [comment] 2022-02-24 04:47
quick google i found this place that you could dump a file for 30 days.
https://ufile.io
don't want to register anywhere to have to download a file.

**Comment by Flash1a** [comment] 2022-02-24 06:43
Ok thanks,  file  upload

https://ufile.io/rapydpls

**Comment by revenz** [comment] 2022-02-24 07:20
hey fellow kiwi :) 

The issue is with that subtitle format, mp4 and mkv do not like it.   I've updated the "Subtitle Remover" node to include "DVB/Teletext Format" and also "Remove all subtitles" (you don't need this but added it in case someone wants to remove all subtitles).

You can update your flow to match this:
![image](https://user-images.githubusercontent.com/958400/155476509-6ac9046b-2d46-497e-9a89-fe40a17006d5.png)

remove the .txt extension, needed to attach to this github issue.
[Convert Plex DVR.json.txt](https://github.com/revenz/FileFlows/files/8130418/Convert.Plex.DVR.json.txt)

Let me know if you are happy with this and it works, then ill close this issue

**Comment by Flash1a** [comment] 2022-02-24 21:09
Thanks that did the trick.

**Closed** 2022-02-24 21:12 UTC
